version: '3.8'

networks:
  hackathon:
    driver: bridge

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web-prod.Dockerfile
    env_file:
      - .env.production
    ports:
      - "80:80"
    networks:
      - hackathon
