version: '3.8'

networks:
  hackathon:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/app
      - ./node_modules/:/app/node_modules
    env_file:
      - .env
    networks:
      - hackathon
    ports:
      - "${PORT}:${PORT}"
  api-prod:
    container_name: api-prod
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - hackathon
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - hackathon
    volumes:
      - pgdata:${POSTGRES_PGDATA}

volumes:
  pgdata:
